/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UpdateCoins;
import Model.Coin;
import Model.MarketSingelton;
import Model.MyWatchlistSingelton;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author mocea
 */
public class CoinList extends javax.swing.JPanel {
    private MarketSingelton ms;
    private MyWatchlistSingelton watchList;
    private UpdateCoins ul;
    
    private DefaultListModel<Coin> dlm;
    private DefaultListModel<Coin> myWallet;
    private ArrayList<Coin> tmpArray;
    private ArrayList<Coin> market;
    
    private boolean showWallet = false;
    
    public boolean isExist(String coin){
        MarketSingelton ms = MarketSingelton.getInstance();
        market = ms.getWholeList();
        boolean a = false;
        for(int i = 0; i < market.size(); i++){
            if(market.get(i).getCoinName().equals(coin)){
                a = true;
            }
        }
        return a;
    }
    
    public void showMarket(){
        ms = MarketSingelton.getInstance();
        this.tmpArray = ms.getWholeList();
        updateScreen(tmpArray);
    }
    
    public void showWatchlist(){       
        watchList = MyWatchlistSingelton.getInstance();
        this.tmpArray = watchList.getWholeList();
        updateScreen(tmpArray);    
    }
    
    public void showPortfolio(ArrayList<Coin> alist){         
        tmpArray = alist;
        updateScreen(tmpArray);    
    }
    
    public void updateScreen(ArrayList<Coin> alist){         
        dlm.clear();
        dlm.addAll(alist);    
    }
    
    public Coin getSelectedCoin(){
        return jlstCoins.getSelectedValue();
    }

    public void addCoin(Coin coin){
        dlm.addElement(coin);
        
    }
    
    public DefaultListModel getModel(){
        return myWallet;
    }
    
    public void setModel(){
        jlstCoins.setModel(myWallet);
    }
    
    
    public void addToWallet(Coin coin){
        myWallet.addElement(coin);
    }
    
    public void setCurrency(String curr){
        for(int i = 0; i < dlm.size(); i++){
            dlm.get(i).setCurrency(curr);
        }
       
    }
    
    public void setChange(String time){
        for(int i = 0; i < dlm.size(); i++){
            dlm.get(i).setPriceChangePeriod(time);
        }
       
    }

    public void removeSelectedItem(){
        int idx = jlstCoins.getSelectedIndex();
        if(idx >= 0){
            dlm.remove(idx);
        }
    }
    
    public CoinList() {
        dlm = new DefaultListModel<Coin>();
        myWallet = new DefaultListModel<Coin>();
        initComponents();
        jlstCoins.setModel(dlm);
        jlstCoins.setCellRenderer(new CoinRender());     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlstCoins = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jlstCoins);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Model.Coin> jlstCoins;
    // End of variables declaration//GEN-END:variables
}
