/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AccountManager;
import Model.Account;
import Model.CoinName;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mor
 */
public class LoginWindow1 extends javax.swing.JFrame {
    RegisterWindow rw;
    MainWindow1 mw;
    AccountManager accMng;
    /**
     * Creates new form LoginWindow1
     */
    public LoginWindow1() {
        accMng = new AccountManager();
        rw = new RegisterWindow();
        
        
        
        initComponents();
        accMng.loadUsers();
       ArrayList<CoinName> list = accMng.getListOfCoinNames();
       
//       for(int i = 0; i < list.size(); i++){
//           System.out.println(list.get(i).getId());
//       }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlbl_Password = new javax.swing.JLabel();
        jtxt_email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jlbl_Email = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jtxt_password = new javax.swing.JPasswordField();
        btnCreateAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSignin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 84, 186));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_Password.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Password.setText("Password");
        jPanel2.add(jlbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jtxt_email.setBackground(new java.awt.Color(25, 84, 186));
        jtxt_email.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jtxt_email.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_email.setText("Email");
        jtxt_email.setToolTipText("");
        jtxt_email.setBorder(null);
        jtxt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_emailActionPerformed(evt);
            }
        });
        jPanel2.add(jtxt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 250, 20));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 300, 20));

        jlbl_Email.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jPanel2.add(jlbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, 70));

        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 300, -1));

        jtxt_password.setBackground(new java.awt.Color(25, 84, 186));
        jtxt_password.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_password.setText("jPasswordField1");
        jtxt_password.setBorder(null);
        jPanel2.add(jtxt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 300, 30));

        btnCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 130, 50));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5a521f032f93c7a8d5137fbc.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, 90));

        btnSignin.setBackground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("SIGN IN");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 130, 50));

        jLabel7.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOT");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 578));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_emailActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        rw.setVisible(true);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:
        String email = jtxt_email.getText();
        String password = jtxt_password.getText();
        Account currAcc = accMng.findAcc(email);
        if(currAcc == null){
            JOptionPane.showMessageDialog(this,"Wrong Email", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        else if(password.equals(currAcc.getPassword())){
            mw = new MainWindow1(currAcc);
            mw.setVisible(true);
            //this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this,"Wrong Password", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_btnSigninActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         accMng.saveData();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbl_Email;
    private javax.swing.JLabel jlbl_Password;
    private javax.swing.JTextField jtxt_email;
    private javax.swing.JPasswordField jtxt_password;
    // End of variables declaration//GEN-END:variables
}
