/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UpdateCoins;
import Controller.UpdatingPrice;
import Model.Account;
import Model.Coin;
import Model.CoinName;
import java.awt.Color;
import java.awt.Component;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class MainWindow1 extends javax.swing.JFrame {
    private Coin coin;
    private UpdateCoins controller;
    private Account acc;
    private TradeWindow bw;
    public static String current_page = "market";
    private Color baseColor = new Color(25,84,186);
    private Color selectedColor = new Color(25,200,255);
    
   
  
    /**
     * Creates new form InventoryWindow
     */
    public MainWindow1(Account acc) {
        this.acc = acc;
        UpdatingPrice up = new UpdatingPrice();
        up.newThread();
        controller = new UpdateCoins();
        
        initComponents();
        refreshScreen();
        System.out.println("acc value : " + acc.getAccValue());
        
        
        
        jPanelMarketbtn.setBackground(selectedColor);
        jbtnRemoveFromWatchList.setVisible(false);
        jlblMainName.setText(acc.getName());
        jlblWalletId.setText(String.valueOf(acc.getWalletNum()));
        
        this.myCoinList.showMarket();
          
        try {
            btnILS.setIcon(new ImageIcon(new URL("https://www.countryflags.io/il/shiny/32.png")));
            btnCAD.setIcon(new ImageIcon(new URL("https://www.countryflags.io/ca/shiny/32.png")));
            btnUSD.setIcon(new ImageIcon(new URL("https://www.countryflags.io/us/shiny/32.png")));
            btnEURO.setIcon(new ImageIcon(new URL("https://www.countryflags.io/eu/shiny/32.png")));
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public  MainWindow1() {
    }
    
    public void refreshScreen(){
        if(current_page.equals("market")){
            btnSell.setVisible(false);
            this.myCoinList.showMarket();
        }
        else if(current_page.equals("watchlist")){
            btnSell.setVisible(false);
            this.myCoinList.showWatchlist();
        }
        else{
            btnSell.setVisible(true);
            this.myCoinList.showPortfolio(acc.getPortfolio());                
        }
        lblAccValue.setText(coin.currencySymbol + acc.getAccountValue());
        lblBuyPower.setText(coin.currencySymbol + String.valueOf(adjustCurrency(coin.currencySymbol,acc.getCash())));
    }
    
    public int adjustCurrency(String currency,int amount ){
        if(currency.equals("$")){
            return amount;
        }
        else if(currency.equals("CA$")){
            double a = amount * 1.21;
            return (int)a;
        }
        else if(currency.equals("€")){
            double a = amount * 0.82;
            return (int)a;
        }
        else if(currency.equals("₪")){
            double a = amount * 3.25;
            return (int)a;
        }
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn1m = new javax.swing.JButton();
        btnILS = new javax.swing.JButton();
        btn1y = new javax.swing.JButton();
        btnUSD = new javax.swing.JButton();
        btnCAD = new javax.swing.JButton();
        jcbSort = new javax.swing.JComboBox<>();
        btnEURO = new javax.swing.JButton();
        myCoinList = new View.CoinList();
        btn1d = new javax.swing.JButton();
        jbtnAddToWatchList = new javax.swing.JButton();
        btnAddCoin = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();
        btn7d = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();
        btnSell = new javax.swing.JButton();
        jbtnRemoveFromWatchList = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelMarket = new javax.swing.JPanel();
        jbtnWatchlist = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnPortfolio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblMainName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblWalletId = new javax.swing.JLabel();
        jPanelPortbtn = new javax.swing.JPanel();
        jPanelWatchbtn = new javax.swing.JPanel();
        jbtnMarket = new javax.swing.JButton();
        jPanelMarketbtn = new javax.swing.JPanel();
        jbtnWithdraw = new javax.swing.JButton();
        jbtnDeposit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblBuyPower = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAccValue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        btnDeleteItem.setText("DEL");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Not Coinbase");

        jPanel1.setBackground(new java.awt.Color(25, 84, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1m.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btn1m.setForeground(new java.awt.Color(255, 255, 255));
        btn1m.setText("1M");
        btn1m.setBorder(null);
        btn1m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1mActionPerformed(evt);
            }
        });
        jPanel1.add(btn1m, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        btnILS.setBackground(new java.awt.Color(102, 255, 102));
        btnILS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnILSActionPerformed(evt);
            }
        });
        jPanel1.add(btnILS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 31));

        btn1y.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btn1y.setForeground(new java.awt.Color(255, 255, 255));
        btn1y.setText("1Y");
        btn1y.setBorder(null);
        btn1y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1yActionPerformed(evt);
            }
        });
        jPanel1.add(btn1y, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        btnUSD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSDActionPerformed(evt);
            }
        });
        jPanel1.add(btnUSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 31));

        btnCAD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCADActionPerformed(evt);
            }
        });
        jPanel1.add(btnCAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 29));

        jcbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price High to Low", "Price Low to High", "Top Gainers", "Top Losers" }));
        jcbSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSortActionPerformed(evt);
            }
        });
        jPanel1.add(jcbSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        btnEURO.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEURO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEUROActionPerformed(evt);
            }
        });
        jPanel1.add(btnEURO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 29));
        jPanel1.add(myCoinList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 350, 503));

        btn1d.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btn1d.setForeground(new java.awt.Color(255, 255, 255));
        btn1d.setText("1D");
        btn1d.setBorder(null);
        btn1d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1dActionPerformed(evt);
            }
        });
        jPanel1.add(btn1d, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jbtnAddToWatchList.setText("Add to Watchlist");
        jbtnAddToWatchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddToWatchListActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddToWatchList, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 740, -1, -1));

        btnAddCoin.setText("ADD");
        btnAddCoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoinActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 67, -1));

        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 79, -1));

        btn7d.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btn7d.setForeground(new java.awt.Color(255, 255, 255));
        btn7d.setText("7D");
        btn7d.setBorder(null);
        btn7d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7dActionPerformed(evt);
            }
        });
        jPanel1.add(btn7d, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lblText.setFont(new java.awt.Font("PingFang TC", 1, 14)); // NOI18N
        lblText.setText("Look for coin:");
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btnSell.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSell.setText("SELL");
        btnSell.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        jPanel1.add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, 100, 60));

        jbtnRemoveFromWatchList.setText("Remove From Watchlist");
        jbtnRemoveFromWatchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveFromWatchListActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRemoveFromWatchList, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 740, -1, -1));

        btnBuy.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy.setText("BUY");
        btnBuy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 100, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMarket.setBackground(new java.awt.Color(25, 84, 186));
        jPanelMarket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnWatchlist.setFont(new java.awt.Font("Zapf Dingbats", 1, 24)); // NOI18N
        jbtnWatchlist.setForeground(new java.awt.Color(255, 255, 255));
        jbtnWatchlist.setText("Watchlist");
        jbtnWatchlist.setBorder(null);
        jbtnWatchlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWatchlistActionPerformed(evt);
            }
        });
        jPanelMarket.add(jbtnWatchlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 260, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portfolio.png"))); // NOI18N
        jPanelMarket.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 50));

        jbtnPortfolio.setFont(new java.awt.Font("Zapf Dingbats", 1, 24)); // NOI18N
        jbtnPortfolio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPortfolio.setText("Portfolio");
        jbtnPortfolio.setBorder(null);
        jbtnPortfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPortfolioActionPerformed(evt);
            }
        });
        jPanelMarket.add(jbtnPortfolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookmark.png"))); // NOI18N
        jPanelMarket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5a521f032f93c7a8d5137fbc.png"))); // NOI18N
        jPanelMarket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internet.png"))); // NOI18N
        jPanelMarket.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jlblMainName.setFont(new java.awt.Font("PT Mono", 1, 24)); // NOI18N
        jlblMainName.setForeground(new java.awt.Color(255, 255, 255));
        jlblMainName.setText("FirstName LastName");
        jPanelMarket.add(jlblMainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Wallet #");
        jPanelMarket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 20));

        jlblWalletId.setForeground(new java.awt.Color(255, 255, 255));
        jlblWalletId.setText("jLabel6");
        jPanelMarket.add(jlblWalletId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 20));

        jPanelPortbtn.setBackground(new java.awt.Color(25, 84, 186));

        javax.swing.GroupLayout jPanelPortbtnLayout = new javax.swing.GroupLayout(jPanelPortbtn);
        jPanelPortbtn.setLayout(jPanelPortbtnLayout);
        jPanelPortbtnLayout.setHorizontalGroup(
            jPanelPortbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelPortbtnLayout.setVerticalGroup(
            jPanelPortbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMarket.add(jPanelPortbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 40, 50));

        jPanelWatchbtn.setBackground(new java.awt.Color(25, 84, 186));

        javax.swing.GroupLayout jPanelWatchbtnLayout = new javax.swing.GroupLayout(jPanelWatchbtn);
        jPanelWatchbtn.setLayout(jPanelWatchbtnLayout);
        jPanelWatchbtnLayout.setHorizontalGroup(
            jPanelWatchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelWatchbtnLayout.setVerticalGroup(
            jPanelWatchbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelMarket.add(jPanelWatchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 40, -1));

        jbtnMarket.setFont(new java.awt.Font("Zapf Dingbats", 1, 24)); // NOI18N
        jbtnMarket.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMarket.setText("Market");
        jbtnMarket.setBorder(null);
        jbtnMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMarketActionPerformed(evt);
            }
        });
        jPanelMarket.add(jbtnMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 60));

        jPanelMarketbtn.setBackground(new java.awt.Color(25, 84, 186));
        jPanelMarketbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelMarket.add(jPanelMarketbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 40, 60));

        jbtnWithdraw.setText("Withdraw");
        jbtnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWithdrawActionPerformed(evt);
            }
        });
        jPanelMarket.add(jbtnWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, -1, 90));

        jbtnDeposit.setText("Deposit");
        jbtnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDepositActionPerformed(evt);
            }
        });
        jPanelMarket.add(jbtnDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, 90));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buying Power:");
        jPanelMarket.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 160, 50));

        lblBuyPower.setFont(new java.awt.Font("Avenir Next", 0, 20)); // NOI18N
        lblBuyPower.setForeground(new java.awt.Color(255, 255, 255));
        lblBuyPower.setText("$1000000");
        jPanelMarket.add(lblBuyPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 160, 50));

        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Account Value:");
        jPanelMarket.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 468, -1, 30));

        lblAccValue.setFont(new java.awt.Font("Avenir Next", 0, 20)); // NOI18N
        lblAccValue.setForeground(new java.awt.Color(255, 255, 255));
        lblAccValue.setText("$1000000");
        jPanelMarket.add(lblAccValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 160, 70));

        jLabel7.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOT");
        jPanelMarket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2.add(jPanelMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        this.myCoinList.removeSelectedItem();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    
    private void btnAddCoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoinActionPerformed
        String coinToAdd = "";
        String a = jTextField.getText();
        boolean isExist = myCoinList.isExist(a);
        if(!isExist){
            ArrayList<CoinName> list = controller.alist();
            for(int i = 0; i < list.size(); i++){
               if(list.get(i).getName().equals(a)){
                   Coin c = controller.createCoin(list.get(i).getId());
                   controller.addCoinToMarket(c);
                   this.myCoinList.showMarket();
                   System.out.println(c.getCoinId());
                   return;
               }
            }
            JOptionPane.showMessageDialog(this,"Couldnt find coin", "Message", JOptionPane.INFORMATION_MESSAGE);
        
           
        }
        else{
            JOptionPane.showMessageDialog(this,"Already Exist", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddCoinActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void btnILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnILSActionPerformed
        // TODO add your handling code here:
        this.myCoinList.setCurrency("ils");
        coin.currency = "ils";
        coin.currencySymbol = "₪";
        refreshScreen();
       
    }//GEN-LAST:event_btnILSActionPerformed

    private void btnUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSDActionPerformed
        // TODO add your handling code here:
        this.myCoinList.setCurrency("usd");
        coin.currency = "usd";
        coin.currencySymbol = "$";
        refreshScreen();
    }//GEN-LAST:event_btnUSDActionPerformed

    private void btnCADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCADActionPerformed
        // TODO add your handling code here:
        this.myCoinList.setCurrency("cad");
        coin.currency = "cad";
         coin.currencySymbol = "CA$";
         refreshScreen();
    }//GEN-LAST:event_btnCADActionPerformed

    private void btnEUROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEUROActionPerformed
        // TODO add your handling code here:
        this.myCoinList.setCurrency("eur");
        coin.currency = "eur";
        coin.currencySymbol = "€";
        refreshScreen();
    }//GEN-LAST:event_btnEUROActionPerformed

    private void jbtnAddToWatchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddToWatchListActionPerformed
        // TODO add your handling code here:      
        controller.addToWatchList(myCoinList.getSelectedCoin());    
    }//GEN-LAST:event_jbtnAddToWatchListActionPerformed

    private void btn1dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1dActionPerformed
        // TODO add your handling code here:
        coin.timePeriod = "price_change_percentage_24h";
        myCoinList.setChange(coin.timePeriod);
        btn1d.setForeground(Color.CYAN);
        btn7d.setForeground(Color.white);
        btn1m.setForeground(Color.white);
        btn1y.setForeground(Color.white);
        refreshScreen();
        
    }//GEN-LAST:event_btn1dActionPerformed

    private void btn7dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7dActionPerformed
        // TODO add your handling code here:
        coin.timePeriod = "price_change_percentage_7d";
        myCoinList.setChange(coin.timePeriod);
        btn1d.setForeground(Color.white);
        btn7d.setForeground(Color.CYAN);
        btn1m.setForeground(Color.white);
        btn1y.setForeground(Color.white);
        refreshScreen();
        
    }//GEN-LAST:event_btn7dActionPerformed

    private void btn1mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1mActionPerformed
        // TODO add your handling code here:
        coin.timePeriod = "price_change_percentage_30d";
        myCoinList.setChange(coin.timePeriod);
        btn1d.setForeground(Color.white);
        btn7d.setForeground(Color.white);
        btn1m.setForeground(Color.CYAN);
        btn1y.setForeground(Color.white);
        refreshScreen();
       
    }//GEN-LAST:event_btn1mActionPerformed

    private void btn1yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1yActionPerformed
        // TODO add your handling code here:
        coin.timePeriod = "price_change_percentage_1y";
        myCoinList.setChange(coin.timePeriod);
        btn1d.setForeground(Color.white);
        btn7d.setForeground(Color.white);
        btn1m.setForeground(Color.white);
        btn1y.setForeground(Color.CYAN);
        refreshScreen();
    }//GEN-LAST:event_btn1yActionPerformed

    private void jcbSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSortActionPerformed
        // TODO add your handling code here:
        controller.sort(jcbSort.getSelectedIndex());
        refreshScreen();
    }//GEN-LAST:event_jcbSortActionPerformed

    private void jbtnWatchlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWatchlistActionPerformed
        // TODO add your handling code here:
        current_page = "watchlist";
        refreshScreen();
        
        jPanelWatchbtn.setBackground(selectedColor);
        jPanelPortbtn.setBackground(baseColor);
        jPanelMarketbtn.setBackground(baseColor);
        
        jbtnAddToWatchList.setVisible(false);
        jbtnRemoveFromWatchList.setVisible(true);
        
    }//GEN-LAST:event_jbtnWatchlistActionPerformed

    private void jbtnMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMarketActionPerformed
        // TODO add your handling code here:
        current_page = "market";
        refreshScreen();

        jPanelMarketbtn.setBackground(selectedColor);
        jPanelWatchbtn.setBackground(baseColor);
        jPanelPortbtn.setBackground(baseColor);
        
        jbtnAddToWatchList.setVisible(true);
        jbtnRemoveFromWatchList.setVisible(false);
    }//GEN-LAST:event_jbtnMarketActionPerformed

    private void jbtnPortfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPortfolioActionPerformed
        // TODO add your handling code here:
        current_page = "portfolio";
        refreshScreen();

        jPanelPortbtn.setBackground(selectedColor);
        jPanelWatchbtn.setBackground(baseColor);
        jPanelMarketbtn.setBackground(baseColor);
        
        jbtnAddToWatchList.setVisible(true);
        jbtnRemoveFromWatchList.setVisible(false);
    }//GEN-LAST:event_jbtnPortfolioActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        bw = new TradeWindow(myCoinList.getSelectedCoin(), acc, "sell");
        bw.setVisible(true);
        System.out.println("liknot ao lo");
    }//GEN-LAST:event_btnSellActionPerformed

    private void jbtnRemoveFromWatchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveFromWatchListActionPerformed
        // TODO add your handling code here:
        controller.removeFromWatchList(myCoinList.getSelectedCoin()); 
        refreshScreen();
    }//GEN-LAST:event_jbtnRemoveFromWatchListActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        bw = new TradeWindow(myCoinList.getSelectedCoin(), acc, "buy");
        bw.setVisible(true);
        System.out.println("liknot ao lo");
    }//GEN-LAST:event_btnBuyActionPerformed

    private void jbtnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDepositActionPerformed
        // TODO add your handling code here:
         int dollarAmount = Integer.parseInt(JOptionPane.showInputDialog("Deposit Amount"));
         acc.addCash(dollarAmount);
         refreshScreen();
         
    }//GEN-LAST:event_jbtnDepositActionPerformed

    private void jbtnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWithdrawActionPerformed
        // TODO add your handling code here:
        if(acc.getCash() > 0){
            int dollarAmount = Integer.parseInt(JOptionPane.showInputDialog("Withdraw Amount"));
            if(dollarAmount <= acc.getCash()){
               acc.removeCash(dollarAmount);
            }
            else{
                Component frame = null;
                JOptionPane.showMessageDialog(frame,"You dont have this amnount, choose smaller amount or sell some coins", "Deposit", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            Component frame = null;
            JOptionPane.showMessageDialog(frame,"You dont have cash to withdraw.", "Withdraw", JOptionPane.INFORMATION_MESSAGE);
        }
        refreshScreen();
    }//GEN-LAST:event_jbtnWithdrawActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1d;
    private javax.swing.JButton btn1m;
    private javax.swing.JButton btn1y;
    private javax.swing.JButton btn7d;
    private javax.swing.JButton btnAddCoin;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCAD;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnEURO;
    private javax.swing.JButton btnILS;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnUSD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMarket;
    private javax.swing.JPanel jPanelMarketbtn;
    private javax.swing.JPanel jPanelPortbtn;
    private javax.swing.JPanel jPanelWatchbtn;
    private javax.swing.JTextField jTextField;
    private javax.swing.JButton jbtnAddToWatchList;
    private javax.swing.JButton jbtnDeposit;
    private javax.swing.JButton jbtnMarket;
    private javax.swing.JButton jbtnPortfolio;
    private javax.swing.JButton jbtnRemoveFromWatchList;
    private javax.swing.JButton jbtnWatchlist;
    private javax.swing.JButton jbtnWithdraw;
    private javax.swing.JComboBox<String> jcbSort;
    private javax.swing.JLabel jlblMainName;
    private javax.swing.JLabel jlblWalletId;
    private javax.swing.JLabel lblAccValue;
    private javax.swing.JLabel lblBuyPower;
    private javax.swing.JLabel lblText;
    private View.CoinList myCoinList;
    // End of variables declaration//GEN-END:variables
}
