/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TradeController;
import Model.Account;
import Model.Coin;
import java.awt.Color;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mor
 */
public class TradeWindow extends javax.swing.JFrame {
    private Account acc;
    private Coin c;
    private int amountInCash;
    private float amountInCoin;
    private String typeOfTrade;
    private TradeController tc;
    private MainWindow1 mw1 = new MainWindow1();
     
    /**
     * Creates new form BuyWindow
     */
    public TradeWindow(Coin coin, Account acc, String typeOfTrade) {
        c = coin;
        this.acc = acc;
        tc = new TradeController();
        this.typeOfTrade = typeOfTrade;
        
        
        initComponents();
        
        if(typeOfTrade.equals("sell")){
            btnSell.setVisible(true);
            btnBuy.setVisible(false);
        }
        else{
            btnSell.setVisible(false);
            btnBuy.setVisible(true);
        }
           
        lblCoinName.setText(coin.getCoinName());
        lblSymbol.setText(coin.getSymbol());
        lblValue.setText(coin.currencySymbol + coin.getCoinValue());
        lblPriceChange.setText(coin.getPriceChange()+ "%");
        if(lblPriceChange.getText().charAt(0) == '-'){
            lblPriceChange.setForeground(Color.red);
        }
        else{
            lblPriceChange.setText("+" + coin.getPriceChange() + "%");
            lblPriceChange.setForeground(Color.green);
        }
        
        try {
            lblIcon.setIcon(new ImageIcon(new URL(coin.getIconURL()))); // NOI18N
        } catch (MalformedURLException ex) {
            Logger.getLogger(CoinRender.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        lblAmountCash.setText("Amount in " + coin.currencySymbol + " :");
        lblAmountCoin.setText("Amount in " + coin.getSymbol() + " :");
       
        
       txtAmountCash.getDocument().addDocumentListener(new SimpleDocumentListener() {
            @Override
            public void update(DocumentEvent e) {
                // Your code here
                amountInCash = 1;

                if(!txtAmountCash.getText().equals("") &&  !txtAmountCash.getText().startsWith("0")){
                    amountInCash =Integer.parseInt(txtAmountCash.getText()); 
                    amountInCoin = (amountInCash / coin.getCoinValue() );
                    txtAmountCoin.setText(String.valueOf(amountInCoin));
                }
                else{
                    txtAmountCoin.setText("0");
                }

            }
        });      
    }
    
    public interface SimpleDocumentListener extends DocumentListener {
    void update(DocumentEvent e);

    @Override
    default void insertUpdate(DocumentEvent e) {
        update(e);
    }
    @Override
    default void removeUpdate(DocumentEvent e) {
        update(e);
    }
    @Override
    default void changedUpdate(DocumentEvent e) {
        update(e);
    }
}

    /**1
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblCoinName = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        lblSymbol = new javax.swing.JLabel();
        lblPriceChange = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAmountCoin = new javax.swing.JLabel();
        lblAmountCash = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtAmountCoin = new javax.swing.JTextField();
        txtAmountCash = new javax.swing.JTextField();
        btnBuy = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trade");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 84, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 70));

        lblCoinName.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblCoinName.setText("Bitcoin");
        jPanel3.add(lblCoinName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 30));

        lblValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValue.setText("$10000");
        jPanel3.add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 30));

        lblSymbol.setText("BTC");
        jPanel3.add(lblSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 20));

        lblPriceChange.setText("+ 1.70%");
        jPanel3.add(lblPriceChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 360, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 200, -1));

        lblAmountCoin.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblAmountCoin.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountCoin.setText("Amount in :");
        jPanel1.add(lblAmountCoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, -1));

        lblAmountCash.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblAmountCash.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountCash.setText("Amount in :");
        jPanel1.add(lblAmountCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 200, -1));

        txtAmountCoin.setEditable(false);
        txtAmountCoin.setBackground(new java.awt.Color(25, 84, 186));
        txtAmountCoin.setForeground(new java.awt.Color(255, 255, 255));
        txtAmountCoin.setText("0");
        txtAmountCoin.setBorder(null);
        txtAmountCoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountCoinActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmountCoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, 30));

        txtAmountCash.setBackground(new java.awt.Color(25, 84, 186));
        txtAmountCash.setForeground(new java.awt.Color(255, 255, 255));
        txtAmountCash.setText("0");
        txtAmountCash.setBorder(null);
        txtAmountCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountCashActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmountCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 30));

        btnBuy.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 50));

        btnSell.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        btnSell.setText("SELL");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        jPanel1.add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 437, 315));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountCoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountCoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountCoinActionPerformed

    private void txtAmountCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountCashActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        if(acc.getCash() >= amountInCash){
            JOptionPane.showMessageDialog(this,"You purchased " + txtAmountCoin.getText() + " " + c.getSymbol() + " for the amount of " + txtAmountCash.getText(), "Purchase", JOptionPane.INFORMATION_MESSAGE);
            tc.coinPurchase(c,amountInCash, acc);
            acc.removeCash(amountInCash);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this," You dont have enough money" , "Buying", JOptionPane.INFORMATION_MESSAGE);
        }
  
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        if(tc.checkAmountIsEnought(acc, c,amountInCoin)){
            tc.coinSelling(c,amountInCash, acc);
            JOptionPane.showMessageDialog(this,"You sold " + txtAmountCoin.getText() + " " + c.getSymbol() + " for the amount of " + txtAmountCash.getText(), "Selling", JOptionPane.INFORMATION_MESSAGE);       
            acc.addCash(amountInCash);
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(this," You dont have enough coins" , "Selling", JOptionPane.INFORMATION_MESSAGE);
        }
      
    }//GEN-LAST:event_btnSellActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAmountCash;
    private javax.swing.JLabel lblAmountCoin;
    private javax.swing.JLabel lblCoinName;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPriceChange;
    private javax.swing.JLabel lblSymbol;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtAmountCash;
    private javax.swing.JTextField txtAmountCoin;
    // End of variables declaration//GEN-END:variables
}
